application: ja-wedding
version: 2
runtime: python27
api_version: 1
threadsafe: true
module: default

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /image
  static_dir: image
- url: /fonts
  static_dir: fonts
- url: /.*
  script: ja.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
